spring.application.name=mbglokal

# KONFIGURASI DATABASE MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_mbg_lokal
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# KONFIGURASI JPA (HIBERNATE)
spring.jpa.hibernate.ddl-auto=update
# true = menampilkan proses query SQL di terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# PENGATURAN SERVER API
# Port untuk menjalankan API
server.port=8080